### ISSUE TITLE
Playback failing from Android App

### ISSUE THREAD

**Issue by nebula-it** [Wellenline/waveline-server#23]
The playback from Android App(v1.5.6) is failing with following error and causes the restart of 'waveline-api'
```
waveline-api | events.js:292
waveline-api |       throw er; // Unhandled 'error' event
waveline-api |       ^
waveline-api |
waveline-api | Error: ENOENT: no such file or directory, unlink '/tmp/3b2d594e-7664-43a5-a701-ef35a2f916c8'
waveline-api | Emitted 'error' event on Stream instance at:
waveline-api |     at WriteStream.emitErr (/app/node_modules/sox-stream/index.js:51:10)
waveline-api |     at WriteStream.emit (events.js:327:22)
waveline-api |     at /app/node_modules/create-temp-file/index.js:15:26
waveline-api |     at FSReqCallback.oncomplete (fs.js:163:23) {
waveline-api |   errno: -2,
waveline-api |   code: 'ENOENT',
waveline-api |   syscall: 'unlink',
waveline-api |   path: '/tmp/3b2d594e-7664-43a5-a701-ef35a2f916c8'
waveline-api | }
waveline-api | npm ERR! code ELIFECYCLE
waveline-api | npm ERR! errno 1
waveline-api | npm ERR! waveline-server@3.0.0 start: `node dist/app.js`
waveline-api | npm ERR! Exit status 1
waveline-api | npm ERR!
waveline-api | npm ERR! Failed at the waveline-server@3.0.0 start script.
waveline-api | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
waveline-api |
waveline-api | npm ERR! A complete log of this run can be found in:
waveline-api | npm ERR!     /root/.npm/_logs/2020-04-24T06_11_14_314Z-debug.log
```

Here are the contents of ` /root/.npm/_logs/2020-04-24T06_11_14_314Z-debug.log` file from docker container:
```
~/.npm/_logs # cat 2020-04-24T06_11_14_314Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v14.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle waveline-server@3.0.0~prestart: waveline-server@3.0.0
6 info lifecycle waveline-server@3.0.0~start: waveline-server@3.0.0
7 verbose lifecycle waveline-server@3.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle waveline-server@3.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle waveline-server@3.0.0~start: CWD: /app
10 silly lifecycle waveline-server@3.0.0~start: Args: [ '-c', 'node dist/app.js' ]
11 silly lifecycle waveline-server@3.0.0~start: Returned: code: 1  signal: null
12 info lifecycle waveline-server@3.0.0~start: Failed to exec start script
13 verbose stack Error: waveline-server@3.0.0 start: `node dist/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid waveline-server@3.0.0
15 verbose cwd /app
16 verbose Linux 3.10.0-1062.9.1.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.0.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error waveline-server@3.0.0 start: `node dist/app.js`
22 error Exit status 1
23 error Failed at the waveline-server@3.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
~/.npm/_logs #
```

**Comment by Wolveix** [comment]
Are you running this using Docker? Or did you build from source? Looking for related issues [elsewhere](https://github.com/gatsbyjs/gatsby/issues/1767), it would seem that this may be caused by a process and/or port conflict.

**Comment by nebula-it** [comment]
Corrects its running in docker, I'm not using the image from docker hub rather cloned the repo and build upon sample-docker-compose.yaml.  Sinces npm is inside docker its highly unlikely that its a port issue. And even on docker host itself port 5000 is not in use.

**Comment by MihkelBaranov** [comment]
It's caused by the transcoding library I'm trying out. I'll see if I can reproduce and fix it somehow

**Comment by nebula-it** [comment]
That explains it since playback was working fine before you added the transcoding support. Looking forward to the fix.
